name: pytest
on:
  push:
    branches: [ pytest ]
  pull_request:
    branches: [ pytest ]

jobs:
  install-python:
    runs-on: ubuntu-latest
  
    steps:
      - uses: actions/checkout@v2
      - name: Install python version
        uses: gabrielfalcao/pyenv-action@v7
        with:
          default: 3.8.6 
          command: pip install -U pip     

      - name: Install dependencies
        run: pip install -r /scripts/mom6nma/requirements.txt --upgrade pip

      - name: test
        run: python /scripts/mom6nma/main.py
